# Generated by Django 5.2.5 on 2025-10-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customeruser',
            table='CustomUser',
        ),
    ]
