# Generated by Django 5.2.5 on 2025-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_alter_customeruser_options_alter_customeruser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
