# Generated by Django 5.2.5 on 2025-10-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_alter_customeruser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
