# Generated by Django 5.2.7 on 2025-10-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0006_alter_customeruser_phone_alter_customeruser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='customeruser',
            table='customuser',
        ),
    ]
