spring.application.name=api-gateway
server.port=8989
server.shutdown=graceful
spring.mvc.problemdetails.enabled=true

######## API Gateway Application Configuration  #########
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.globalcors.cors-configurations["[/**]"].allowed-origin-patterns="*"
spring.cloud.gateway.globalcors.cors-configurations["[/**]"].allowed-methods="*"
spring.cloud.gateway.globalcors.cors-configurations["[/**]"].allowed-headers="*"
spring.cloud.gateway.globalcors.cors-configurations["[/**]"].allow-credentials=true

spring.cloud.gateway.routes[0].id=trip-service
spring.cloud.gateway.routes[0].uri=${TRIP_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[0].predicates[0]=Path=/trips/**, /pricing/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/trips/?(?<segment>.*), /trips/${segment}
spring.cloud.gateway.routes[0].filters[1]=RewritePath=/pricing/?(?<segment>.*), /pricing/${segment}

spring.cloud.gateway.routes[1].id=driver-service
spring.cloud.gateway.routes[1].uri=${DRIVER_SERVICE_URL:http://localhost:3000}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/drivers/**, /trpc/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/drivers/?(?<segment>.*), /api/drivers/${segment}

spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=${USER_SERVICE_URL:http://localhost:8000}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/**, /admin/**

spring.cloud.gateway.routes[3].id=openapi
spring.cloud.gateway.routes[3].uri=http://localhost:${server.port}
spring.cloud.gateway.routes[3].predicates[0]=Path=/v3/api-docs/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs

######## Actuator Configuration  #########
management.info.git.mode=full
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=false
management.tracing.sampling.probability=1.0

######## Swagger Configuration  #########
springdoc.swagger-ui.use-root-path=true
springdoc.swagger-ui.urls[0].name=trip
springdoc.swagger-ui.urls[0].url=/v3/api-docs/trip
springdoc.swagger-ui.urls[1].name=driver
springdoc.swagger-ui.urls[1].url=/v3/api-docs/driver
springdoc.swagger-ui.urls[2].name=user
springdoc.swagger-ui.urls[2].url=/v3/api-docs/user
