server:
  error:
    include-message: always
    include-stacktrace: never

logging:
  level:
    com.uitgo.trip: DEBUG
    feign: INFO

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

external:
  driver-service:
    base-url: http://localhost:8083

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

resilience4j:
  circuitbreaker:
    instances:
      driverSearch:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
