services:
    driver-service:
        build: .
        depends_on:
            - redis
        env_file:
            - .env
        ports:
            - "3000:3000"

    redis:
        image: redis:7
