services:
    app:
        build: .
        depends_on:
            - redis
        environment:
            DATABASE_URL: "${DATABASE_URL}"
            REDIS_HOST: redis
            REDIS_PORT: 6379
        ports:
            - "3000:3000"

    redis:
        image: redis:7
