# Basic settings
bind 0.0.0.0
protected-mode no
appendonly yes

# Cluster settings (for Redis Cluster)
cluster-enabled yes
cluster-node-timeout 5000
# Optional: Allows cluster to function even if some slots are uncovered
cluster-require-full-coverage no

# IO Threads for multi-core
io-threads 2
io-threads-do-reads yes