name: Django CI cho UserService

on:
  push:
    branches: [ "UserService" ]
    paths:
      - 'UserService/**'  # <-- SỬA: Chỉ kích hoạt khi có thay đổi trong thư mục UserService/
  pull_request:
    branches: [ "UserService" ]
    paths:
      - 'UserService/**'  # <-- SỬA: Chỉ kích hoạt khi có thay đổi trong thư mục UserService/

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13] # Bạn dùng 3.13 cũng được, nhưng 3.11, 3.12 ổn định hơn

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Bây giờ sẽ tìm thấy file

    - name: Run Tests
      # THÊM DÒNG NÀY:
      working-directory: ./UserService 
      run: |
        python manage.py test # Bây giờ sẽ tìm thấy manage.py
